version: 2.1

orbs:
  wp-svn: studiopress/wp-svn@0.1
  php: circleci/php@1.1

jobs:
  lint:
    docker:
      - image: php:8.2.7-apache-bullseye
    steps:
      - checkout
      - run: php -i
      - php/install-packages
      - run: phpcs

workflows:
  test-deploy:
    jobs:
      - lint
      - approval-for-deploy-tested-up-to-bump:
          requires:
            - lint
          type: approval
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
